### PR TITLE
refactor: remove deprecated functions

### PR DESCRIPTION
**Pull request by zi**
With latest `fp-ts` updates some functions has been deprecated. Goal of this PR is to remove the deprecated functions.
Some info: https://stackoverflow.com/a/67875549/657582

### CODE REVIEW

**Comment by dinoiam** [comment]
@zi Why did you replace pipe with flow?

**Comment by zi** [comment]
> @zi Why did you replace pipe with flow? For the rest, it seems fine to me.

I've been misled by this comment 
```
/**
 * Use [`pipe`](https://gcanti.github.io/fp-ts/modules/function.ts.html#flow) from `function` module instead.
 *
 * @since 2.0.0
 * @deprecated
 */
```
but I see now that the `function` module exports also the `pipe` function

**Review by dinoiam — APPROVED** [review]
Since you already transform all the `pipe` to `flow` and since they are equivalent I don't think it's necessary to rollback. Looks good to me! :D

**Comment by enricopolanski** [comment]
Flow allows you to "curry" better.

E.g.

```ts
import { flow, pipe } from "fp-ts/function";

const inc = (x: number) => x + 1;

const double = (x: number) => x * 2;

const doublePlusOne = flow(inc, double);

const doublePlusOneAlt = pipe(inc, double) // errore

/*
  Argument of type '(x: number) => number' is not assignable to parameter of type 'number'.
*/
```

Nel nostro caso penso vada benissimo usare `flow` _togliendo_ il parametro aggiuntivo.

**Pull request merged**
